### PR TITLE
Fixed typographical error, changed accross to across in README.

### PR DESCRIPTION
**Pull request by orthographic-pedant**
@iconara, I've corrected a typographical error in the documentation of the [cql-rb](https://github.com/iconara/cql-rb) project. You should be able to merge this pull request automatically. However, if this was intentional or if you enjoy living in linguistic squalor, please let me know and [create an issue](https://github.com/thoppe/orthographic-pedant/issues/new) on my home repository.

### CODE REVIEW

**Comment by iconara** [comment]
I've reported your bot to GitHub.

**Comment by thoppe** [comment]
Presumably you've told them about the hundreds of successful PR merged over the last few days. If, on the off chance you dislike something about @orthographic-pedant, I suggest creating an issue and we can work together to make the world a better place!

**Comment by iconara** [comment]
I don't want to have to opt out of every single bot that people like you think are a service to others. I didn't ask for this. What makes you different from people who run spam bots?

**Comment by thoppe** [comment]
> What makes you different from people who run spam bots?

Presumably intent. IMHO this is no different than a human making poor commit to your code in the first place. I view github more like wikipedia -- the code is out there an ready to be edited! I know that github has ability to ban users -- feel free to do that for @orthographic-pedant. 

If you like, I could create the first user blacklist just for you. If you think it's worth it, please create an issue.

**Comment by thoppe** [comment]
You are now on an ignore list:

https://github.com/thoppe/orthographic-pedant/blob/master/blacklists/users.txt

so you shouldn't hear from me again (for this project anyways!). Thanks for indirectly helping the project!

https://github.com/thoppe/orthographic-pedant/issues/11

**Pull request closed without merging**
